### ISSUE TITLE
Restrict Search Area to a reasonable size to help users navigate easier and filter out unreasonable addresses

### ISSUE THREAD

**Issue by NolanChan** [codelaboc/CA-Stormwater-Data-Challenge#12]
Based off the [options param for the GeoCoder object](https://github.com/mapbox/mapbox-gl-geocoder/blob/master/API.md), I'm thinking we should add something for `proximity` and `bbox` so users aren't confused with superfluous addresses in the dropdown for the search box:

-   `options.proximity` **\[[Object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object)]** a proximity argument: this is
        a geographical point given as an object with latitude and longitude
        properties. Search results closer to this point will be given
        higher priority.
-   `options.bbox` **\[[Array](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array)]** a bounding box argument: this is
        a bounding box given as an array in the format [minX, minY, maxX, maxY].
        Search results will be limited to the bounding box.

**Comment by honzo0481** [comment]
it's a good idea. just a little larger than the bounds of the tilesets is probably a good start. 
these are the tributary bounds. -117.8,33.4,-117.5,33.7

**Comment by honzo0481** [comment]
closed by #13
