### ISSUE TITLE
Get geo data into Mapbox

### ISSUE THREAD

**Issue by theresaluu** [codelaboc/CA-Stormwater-Data-Challenge#3]
- census blocks
 - storm drains

**Comment by theresaluu** [comment]
Once we get our access tokens we can proceed with instructions here to add to our website: https://www.mapbox.com/mapbox-gl-js/api/

**Comment by leighphan** [comment]
Uploaded the following GIS data layers to MapBox: OC Census Blocks, Discharge Points, Discharge Tributaries.
We're using one of the MapBox default styles, called "Bright". We've named the style "UrbanDroolOCData" - to be added to the HTML page.
